/*
 * davinci_read_regs.c
 *
 *
 *  Created on: 20.01.2011
 *      Author: Klaus Schwarzkopf <schwarzkopf@sensortherm.de>
 *
 * This package is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#include <linux/log2.h>
#include <linux/slab.h>
#include <linux/kernel.h>
#include <linux/module.h>
#include <linux/version.h> 
#include <linux/platform_device.h>
#include <mach/hardware.h>
#include <mach/io.h>
#include <asm/io.h>


#if defined(ARCH_DAVINCI_DM355)
#include "../davinci/dm355_ccdc_regs.h"
#include "../../../char/dm355_ipipe_hw.h"
#endif

#if defined(CONFIG_MACH_DM365_LEOPARD)
	#include "../davinci/dm365_ccdc_regs.h"

	#if LINUX_VERSION_CODE == KERNEL_VERSION(2,6,37)
		#include "../davinci/vpbe_venc_regs.h"
		#include "../davinci/vpbe_osd_regs.h"
	#else
		#include "vpbe_venc_regs.h"
		#include "vpbe_osd_regs.h"
	#endif
#endif



extern u32 venc_reg_in(u32 offset);

//#define READ_REG(x) (printk( KERN_INFO "%s\t 0x%08x 0x%08x\n", #x, x, venc_reg_in(x)))
#define BASE_REGISTER_GPIO 					0x01C67000
#define BASE_REGISTER_PRTCIF 				0x01C69000
#define BASE_REGISTER_KEYSCAN 				0x01C69400
#define BASE_REGISTER_VPSS					0x01c70000


//#define BASE_REGISTER_DM355_END_ADDR			0x01c71404
//#define BASE_REGISTER_DM355_SIZE				(BASE_REGISTER_DM355_END_ADDR-BASE_REGISTER_START_ADDR)

#define OFFSET_BASE_REGISTER_DM355_VPSSCLK	0x0000
#define OFFSET_BASE_REGISTER_DM355_H3A		0x0080
#define OFFSET_BASE_REGISTER_DM355_IPIPEIF	0x0100
#define OFFSET_BASE_REGISTER_DM355_OSD		0x0200
#define OFFSET_BASE_REGISTER_DM355_VENC		0x0400
#define OFFSET_BASE_REGISTER_DM355_CCDC		0x0600
#define OFFSET_BASE_REGISTER_DM355_VPSSBL	0x0800
#define OFFSET_BASE_REGISTER_DM355_IPIPE	0x1000


#define OFFSET_BASE_REGISTER_DM365_ISP		0x0000 //ISP System Configuration
#define OFFSET_BASE_REGISTER_DM365_VPSS		0x0200 //VPSS System Configuration and VPBE Clock Control
#define OFFSET_BASE_REGISTER_DM365_RSZ		0x0400 //Resizer
#define OFFSET_BASE_REGISTER_DM365_IPIPE	0x0800 //Image Pipe
#define OFFSET_BASE_REGISTER_DM365_ISIF		0x1000 //Image Sensor Interface
#define OFFSET_BASE_REGISTER_DM365_IPIPEIF	0x1200 //Image Pipe Interface
#define OFFSET_BASE_REGISTER_DM365_H3A		0x1400 //Hardware 3A


#define OFFSET_BASE_REGISTER_DM365_OSD		0x1C00 //VPBE On-Screen Display
#define OFFSET_BASE_REGISTER_DM365_VENC		0x1E00 //VPBE Video Encoder


#define DM365_PINMUX0						0x01C40000
#define DM365_PINMUX1						0x01C40004
#define DM365_PINMUX2						0x01C40008
#define DM365_PINMUX3						0x01C4000C
#define DM365_PINMUX4						0x01C40010



#define VPSS_CLK_CTRL						0x01C40044
#define VPBE_CLK_CTRL 						0x00


#define CPIO_PID			0x00
#define CPIO_BITEN			0x08

#define CPIO_DIR01			0x10
#define CPIO_OUT_DATA01		0x14
#define CPIO_SET_DATA01		0x18
#define CPIO_CLR_DATA01		0x1C
#define CPIO_IN_DATA01		0x20

#define CPIO_SET_RIS_TRIG01	0x24
#define CPIO_CLR_RIS_TRIG01	0x28
#define CPIO_SET_FAL_TRIG01	0x2C
#define CPIO_CLR_FAL_TRIG01	0x30
#define CPIO_INTSTAT01		0x34

#define CPIO_DIR23			0x38
#define CPIO_OUT_DATA23		0x3C
#define CPIO_SET_DATA23		0x40
#define CPIO_CLR_DATA23		0x44
#define CPIO_IN_DATA23		0x48

#define CPIO_DIR45			0x60
#define CPIO_OUT_DATA45		0x64
#define CPIO_SET_DATA45		0x68
#define CPIO_CLR_DATA45		0x6C
#define CPIO_IN_DATA45		0x70

#define CPIO_DIR6			0x88
#define CPIO_OUT_DATA6		0x8C
#define CPIO_SET_DATA6		0x90
#define CPIO_CLR_DATA6		0x94
#define CPIO_IN_DATA6		0x98

#define CPIO_SET_RIS_TRIG6	0x9C
#define CPIO_CLR_RIS_TRIG6	0xA0
#define CPIO_SET_FAL_TRIG6	0xA4
#define CPIO_CLR_FAL_TRIG6	0xA8
#define CPIO_INTSTAT6		0xAC


void __force __iomem * base_addr = IO_ADDRESS(BASE_REGISTER_VPSS);
u32 base_offset = 0;


static inline u32 regr(u32 offset) {
	return __raw_readl(base_addr + base_offset + offset);
}

static inline void regw(u32 val, u32 offset) {
	__raw_writel(val, base_addr + base_offset + offset);

}
static inline u32 regwrite(u32 val, u32 reg) {
	__raw_writel(val, IO_ADDRESS(reg));
	return __raw_readl(IO_ADDRESS(reg));

}

#define READ_REG_OFFSET(x) (printk( KERN_INFO "%20s\t 0x%08x 0x%08x\n", #x, x, regr(x)))

#define READ_REG(x) (printk( KERN_INFO "%20s\t 0x%08x 0x%08x\n", #x, x, __raw_readl(IO_ADDRESS(x))))

#define WRITE_REG(reg, val) ( printk( KERN_INFO "%20s\t 0x%08x 0x%08x\n", #reg, reg, regwrite(val, reg)))

#define SET_BASE_OFFSET(x) (printk( KERN_INFO "\n%s\t 0x%08x\n\n", #x, base_offset=x))
#define SET_BASE_ADR(x) { \
	base_addr = IO_ADDRESS(x); \
	base_offset = 0; \
	printk( KERN_INFO "\n%s\t 0x%08x\n\n", #x, x);}


#if defined(CONFIG_MACH_DM365_LEOPARD)
static void print_regs_dm365(void) {

printk( KERN_INFO "\nDM365\n\n");

//u32 vpss_clk_ctrl =  __raw_readl(IO_ADDRESS(VPSS_CLK_CTRL));
//__raw_writel(vpss_clk_ctrl | (1<<2), IO_ADDRESS(VPSS_CLK_CTRL));

READ_REG(DM365_PINMUX0);
READ_REG(DM365_PINMUX1);
READ_REG(DM365_PINMUX2);
READ_REG(DM365_PINMUX3);
READ_REG(DM365_PINMUX4);
READ_REG(VPSS_CLK_CTRL);

//WRITE_REG(VPSS_CLK_CTRL, 0x1c);


SET_BASE_ADR(BASE_REGISTER_GPIO)

READ_REG_OFFSET(CPIO_PID);//0x00
READ_REG_OFFSET(CPIO_BITEN);//0x08

READ_REG_OFFSET(CPIO_DIR01);//0x10
READ_REG_OFFSET(CPIO_OUT_DATA01);//0x14
READ_REG_OFFSET(CPIO_SET_DATA01);//0x18
READ_REG_OFFSET(CPIO_CLR_DATA01);//0x1C
READ_REG_OFFSET(CPIO_IN_DATA01);//0x20

READ_REG_OFFSET(CPIO_SET_RIS_TRIG01);//0x24
READ_REG_OFFSET(CPIO_CLR_RIS_TRIG01);//0x28
READ_REG_OFFSET(CPIO_SET_FAL_TRIG01);//0x2C
READ_REG_OFFSET(CPIO_CLR_FAL_TRIG01);//0x30
READ_REG_OFFSET(CPIO_INTSTAT01);//0x34

READ_REG_OFFSET(CPIO_DIR23);//0x38
READ_REG_OFFSET(CPIO_OUT_DATA23);//0x3C
READ_REG_OFFSET(CPIO_SET_DATA23);//0x40
READ_REG_OFFSET(CPIO_CLR_DATA23);//0x44
READ_REG_OFFSET(CPIO_IN_DATA23);//0x48

READ_REG_OFFSET(CPIO_DIR45);//0x60
READ_REG_OFFSET(CPIO_OUT_DATA45);//0x64
READ_REG_OFFSET(CPIO_SET_DATA45);//0x68
READ_REG_OFFSET(CPIO_CLR_DATA45);//0x6C
READ_REG_OFFSET(CPIO_IN_DATA45);//0x70

READ_REG_OFFSET(CPIO_DIR6);//0x88
READ_REG_OFFSET(CPIO_OUT_DATA6);//0x8C
READ_REG_OFFSET(CPIO_SET_DATA6);//0x90
READ_REG_OFFSET(CPIO_CLR_DATA6);//0x94
READ_REG_OFFSET(CPIO_IN_DATA6);//0x98

READ_REG_OFFSET(CPIO_SET_RIS_TRIG6);//0x9C
READ_REG_OFFSET(CPIO_CLR_RIS_TRIG6);//0xA0
READ_REG_OFFSET(CPIO_SET_FAL_TRIG6);//0xA4
READ_REG_OFFSET(CPIO_CLR_FAL_TRIG6);//0xA8
READ_REG_OFFSET(CPIO_INTSTAT6);//0xAC



SET_BASE_OFFSET(OFFSET_BASE_REGISTER_DM365_VPSS);

READ_REG_OFFSET(VPBE_CLK_CTRL);


SET_BASE_ADR(BASE_REGISTER_VPSS)

SET_BASE_OFFSET(OFFSET_BASE_REGISTER_DM365_ISIF);

READ_REG_OFFSET(SYNCEN					);//00
READ_REG_OFFSET(MODESET					);//04
READ_REG_OFFSET(HDW					);//08
READ_REG_OFFSET(VDW					);//0c
READ_REG_OFFSET(PPLN					);//10
READ_REG_OFFSET(LPFR					);//14
READ_REG_OFFSET(SPH					);//18
READ_REG_OFFSET(LNH					);//1c
READ_REG_OFFSET(SLV0					);//20
READ_REG_OFFSET(SLV1					);//24
READ_REG_OFFSET(LNV					);//28
READ_REG_OFFSET(CULH					);//2c
READ_REG_OFFSET(CULV					);//30
READ_REG_OFFSET(HSIZE					);//34
READ_REG_OFFSET(SDOFST					);//38
READ_REG_OFFSET(CADU					);//3c
READ_REG_OFFSET(CADL					);//40
READ_REG_OFFSET(LINCFG0					);//44
READ_REG_OFFSET(LINCFG1					);//48
READ_REG_OFFSET(CCOLP					);//4c
READ_REG_OFFSET(CRGAIN					);//50
READ_REG_OFFSET(CGRGAIN					);//54
READ_REG_OFFSET(CGBGAIN					);//58
READ_REG_OFFSET(CBGAIN					);//5c
READ_REG_OFFSET(COFSTA					);//60
READ_REG_OFFSET(FLSHCFG0				);//64
READ_REG_OFFSET(FLSHCFG1				);//68
READ_REG_OFFSET(FLSHCFG2				);//6c
READ_REG_OFFSET(VDINT0					);//70
READ_REG_OFFSET(VDINT1					);//74
READ_REG_OFFSET(VDINT2					);//78
READ_REG_OFFSET(MISC					);//7c
READ_REG_OFFSET(CGAMMAWD				);//80
READ_REG_OFFSET(REC656IF				);//84
READ_REG_OFFSET(CCDCFG					);//88
/*****************************************************
* Defect Correction registers
*****************************************************/
READ_REG_OFFSET(DFCCTL					);//8c
READ_REG_OFFSET(VDFSATLV				);//90
READ_REG_OFFSET(DFCMEMCTL				);//94
READ_REG_OFFSET(DFCMEM0					);//98
READ_REG_OFFSET(DFCMEM1					);//9c
READ_REG_OFFSET(DFCMEM2					);//a0
READ_REG_OFFSET(DFCMEM3					);//a4
READ_REG_OFFSET(DFCMEM4					);//a8
/****************************************************
* Black Clamp registers
****************************************************/
READ_REG_OFFSET(CLAMPCFG				);//ac
READ_REG_OFFSET(CLDCOFST				);//b0
READ_REG_OFFSET(CLSV					);//b4
READ_REG_OFFSET(CLHWIN0					);//b8
READ_REG_OFFSET(CLHWIN1					);//bc
READ_REG_OFFSET(CLHWIN2					);//c0
READ_REG_OFFSET(CLVRV					);//c4
READ_REG_OFFSET(CLVWIN0					);//c8
READ_REG_OFFSET(CLVWIN1					);//cc
READ_REG_OFFSET(CLVWIN2					);//d0
READ_REG_OFFSET(CLVWIN3					);//d4
/****************************************************
* Lense Shading Correction
****************************************************/
READ_REG_OFFSET(DATAHOFST				);//d8
READ_REG_OFFSET(DATAVOFST				);//dc
READ_REG_OFFSET(LSCHVAL					);//e0
READ_REG_OFFSET(LSCVVAL					);//e4
READ_REG_OFFSET(TWODLSCCFG				);//e8
READ_REG_OFFSET(TWODLSCOFST				);//ec
READ_REG_OFFSET(TWODLSCINI				);//f0
READ_REG_OFFSET(TWODLSCGRBU				);//f4
READ_REG_OFFSET(TWODLSCGRBL				);//f8
READ_REG_OFFSET(TWODLSCGROF				);//fc
READ_REG_OFFSET(TWODLSCORBU				);//100
READ_REG_OFFSET(TWODLSCORBL				);//104
READ_REG_OFFSET(TWODLSCOROF				);//108
READ_REG_OFFSET(TWODLSCIRQEN				);//10c
READ_REG_OFFSET(TWODLSCIRQST				);//110
/****************************************************
* Data formatter
****************************************************/
READ_REG_OFFSET(FMTCFG					);//114
READ_REG_OFFSET(FMTPLEN					);//118
READ_REG_OFFSET(FMTSPH					);//11c
READ_REG_OFFSET(FMTLNH					);//120
READ_REG_OFFSET(FMTSLV					);//124
READ_REG_OFFSET(FMTLNV					);//128
READ_REG_OFFSET(FMTRLEN					);//12c
READ_REG_OFFSET(FMTHCNT					);//130
READ_REG_OFFSET(FMTAPTR_BASE				);//134
READ_REG_OFFSET(FMTPGMVF0				);//174
READ_REG_OFFSET(FMTPGMVF1				);//178
READ_REG_OFFSET(FMTPGMAPU0				);//17c
READ_REG_OFFSET(FMTPGMAPU1				);//180
READ_REG_OFFSET(FMTPGMAPS0				);//184
READ_REG_OFFSET(FMTPGMAPS1				);//188
READ_REG_OFFSET(FMTPGMAPS2				);//18c
READ_REG_OFFSET(FMTPGMAPS3				);//190
READ_REG_OFFSET(FMTPGMAPS4				);//194
READ_REG_OFFSET(FMTPGMAPS5				);//198
READ_REG_OFFSET(FMTPGMAPS6				);//19c
READ_REG_OFFSET(FMTPGMAPS7				);//1a0
/************************************************
* Color Space Converter
************************************************/
READ_REG_OFFSET(CSCCTL					);//1a4
READ_REG_OFFSET(CSCM0					);//1a8
READ_REG_OFFSET(CSCM1					);//1ac
READ_REG_OFFSET(CSCM2					);//1b0
READ_REG_OFFSET(CSCM3					);//1b4
READ_REG_OFFSET(CSCM4					);//1b8
READ_REG_OFFSET(CSCM5					);//1bc
READ_REG_OFFSET(CSCM6					);//1c0
READ_REG_OFFSET(CSCM7					);//1c4
READ_REG_OFFSET(OBWIN0					);//1c8
READ_REG_OFFSET(OBWIN1					);//1cc
READ_REG_OFFSET(OBWIN2					);//1d0
READ_REG_OFFSET(OBWIN3					);//1d4
READ_REG_OFFSET(OBVAL0					);//1d8
READ_REG_OFFSET(OBVAL1					);//1dc
READ_REG_OFFSET(OBVAL2					);//1e0
READ_REG_OFFSET(OBVAL3					);//1e4
READ_REG_OFFSET(OBVAL4					);//1e8
READ_REG_OFFSET(OBVAL5					);//1ec
READ_REG_OFFSET(OBVAL6					);//1f0
READ_REG_OFFSET(OBVAL7					);//1f4
READ_REG_OFFSET(CLKCTL					);//1f8


SET_BASE_OFFSET(OFFSET_BASE_REGISTER_DM365_VENC);


READ_REG_OFFSET(VENC_VMOD				);//00
READ_REG_OFFSET(VENC_VIDCTL				);//04
READ_REG_OFFSET(VENC_VDPRO				);//08
READ_REG_OFFSET(VENC_SYNCCTL				);//0C
READ_REG_OFFSET(VENC_HSPLS				);//10
READ_REG_OFFSET(VENC_VSPLS				);//14
READ_REG_OFFSET(VENC_HINT				);//18
READ_REG_OFFSET(VENC_HSTART				);//1C
READ_REG_OFFSET(VENC_HVALID				);//20
READ_REG_OFFSET(VENC_VINT				);//24
READ_REG_OFFSET(VENC_VSTART				);//28
READ_REG_OFFSET(VENC_VVALID				);//2C
READ_REG_OFFSET(VENC_HSDLY				);//30
READ_REG_OFFSET(VENC_VSDLY				);//34
READ_REG_OFFSET(VENC_YCCCTL				);//38
READ_REG_OFFSET(VENC_RGBCTL				);//3C
READ_REG_OFFSET(VENC_RGBCLP				);//40
READ_REG_OFFSET(VENC_LINECTL				);//44
READ_REG_OFFSET(VENC_CULLLINE				);//48
READ_REG_OFFSET(VENC_LCDOUT				);//4C
READ_REG_OFFSET(VENC_BRTS				);//50
READ_REG_OFFSET(VENC_BRTW				);//54
READ_REG_OFFSET(VENC_ACCTL				);//58
READ_REG_OFFSET(VENC_PWMP				);//5C
READ_REG_OFFSET(VENC_PWMW				);//60
READ_REG_OFFSET(VENC_DCLKCTL				);//64
READ_REG_OFFSET(VENC_DCLKPTN0				);//68
READ_REG_OFFSET(VENC_DCLKPTN1				);//6C
READ_REG_OFFSET(VENC_DCLKPTN2				);//70
READ_REG_OFFSET(VENC_DCLKPTN3				);//74
READ_REG_OFFSET(VENC_DCLKPTN0A				);//78
READ_REG_OFFSET(VENC_DCLKPTN1A				);//7C
READ_REG_OFFSET(VENC_DCLKPTN2A				);//80
READ_REG_OFFSET(VENC_DCLKPTN3A				);//84
READ_REG_OFFSET(VENC_DCLKHS				);//88
READ_REG_OFFSET(VENC_DCLKHSA				);//8C
READ_REG_OFFSET(VENC_DCLKHR				);//90
READ_REG_OFFSET(VENC_DCLKVS				);//94
READ_REG_OFFSET(VENC_DCLKVR				);//98
READ_REG_OFFSET(VENC_CAPCTL				);//9C
READ_REG_OFFSET(VENC_CAPDO				);//A0
READ_REG_OFFSET(VENC_CAPDE				);//A4
READ_REG_OFFSET(VENC_ATR0				);//A8
READ_REG_OFFSET(VENC_ATR1				);//AC
READ_REG_OFFSET(VENC_ATR2				);//B0
READ_REG_OFFSET(VENC_VSTAT				);//B8
READ_REG_OFFSET(VENC_RAMADR				);//BC
READ_REG_OFFSET(VENC_RAMPORT				);//C0
READ_REG_OFFSET(VENC_DACTST				);//C4
READ_REG_OFFSET(VENC_YCOLVL				);//C8
READ_REG_OFFSET(VENC_SCPROG				);//CC
READ_REG_OFFSET(VENC_CVBS				);//DC
READ_REG_OFFSET(VENC_CMPNT				);//E0
READ_REG_OFFSET(VENC_ETMG0				);//E4
READ_REG_OFFSET(VENC_ETMG1				);//E8
READ_REG_OFFSET(VENC_ETMG2				);//EC
READ_REG_OFFSET(VENC_ETMG3				);//F0
READ_REG_OFFSET(VENC_DACSEL				);//F4
READ_REG_OFFSET(VENC_ARGBX0				);//100
READ_REG_OFFSET(VENC_ARGBX1				);//104
READ_REG_OFFSET(VENC_ARGBX2				);//108
READ_REG_OFFSET(VENC_ARGBX3				);//10C
READ_REG_OFFSET(VENC_ARGBX4				);//110
READ_REG_OFFSET(VENC_DRGBX0				);//114
READ_REG_OFFSET(VENC_DRGBX1				);//118
READ_REG_OFFSET(VENC_DRGBX2				);//11C
READ_REG_OFFSET(VENC_DRGBX3				);//120
READ_REG_OFFSET(VENC_DRGBX4				);//124
READ_REG_OFFSET(VENC_VSTARTA				);//128
READ_REG_OFFSET(VENC_OSDCLK0				);//12C
READ_REG_OFFSET(VENC_OSDCLK1				);//130
READ_REG_OFFSET(VENC_HVLDCL0				);//134
READ_REG_OFFSET(VENC_HVLDCL1				);//138
READ_REG_OFFSET(VENC_OSDHADV				);//13C
READ_REG_OFFSET(VENC_CLKCTL				);//140
READ_REG_OFFSET(VENC_GAMCTL				);//144
READ_REG_OFFSET(VENC_XHINTVL				);//174


#if 0
/* VPBE Global Registers */
READ_REG_OFFSET(VPBE_PID				);//0
READ_REG_OFFSET(VPBE_PCR				);//4

/* VPSS CLock Registers */
READ_REG_OFFSET(VPSSCLK_PID				);//00
READ_REG_OFFSET(VPSSCLK_CLKCTRL				);//04

/* VPSS Buffer Logic Registers */
READ_REG_OFFSET(VPSSBL_PID				);//00
READ_REG_OFFSET(VPSSBL_PCR				);//04
READ_REG_OFFSET(VPSSBL_BCR				);//08
READ_REG_OFFSET(VPSSBL_INTSTAT				);//0C
READ_REG_OFFSET(VPSSBL_INTSEL				);//10
READ_REG_OFFSET(VPSSBL_EVTSEL				);//14
READ_REG_OFFSET(VPSSBL_MEMCTRL				);//18
READ_REG_OFFSET(VPSSBL_CCDCMUX				);//1C

/* DM365 ISP5 system configuration */
READ_REG_OFFSET(ISP5_PID				);//0
READ_REG_OFFSET(ISP5_PCCR				);//4
READ_REG_OFFSET(ISP5_BCR				);//8
READ_REG_OFFSET(ISP5_INTSTAT				);//C
READ_REG_OFFSET(ISP5_INTSEL1				);//10
READ_REG_OFFSET(ISP5_INTSEL2				);//14
READ_REG_OFFSET(ISP5_INTSEL3				);//18
READ_REG_OFFSET(ISP5_EVTSEL				);//1c
READ_REG_OFFSET(ISP5_CCDCMUX				);//20

#endif


SET_BASE_OFFSET(OFFSET_BASE_REGISTER_DM365_OSD);
/* VPBE On-Screen Display Subsystem Registers (OSD) */
READ_REG_OFFSET(OSD_MODE				);//00
READ_REG_OFFSET(OSD_VIDWINMD				);//04
READ_REG_OFFSET(OSD_OSDWIN0MD				);//08
READ_REG_OFFSET(OSD_OSDWIN1MD				);//0C
READ_REG_OFFSET(OSD_OSDATRMD				);//0C
READ_REG_OFFSET(OSD_RECTCUR				);//10
READ_REG_OFFSET(OSD_VIDWIN0OFST				);//18
READ_REG_OFFSET(OSD_VIDWIN1OFST				);//1C
READ_REG_OFFSET(OSD_OSDWIN0OFST				);//20
READ_REG_OFFSET(OSD_OSDWIN1OFST				);//24
READ_REG_OFFSET(OSD_VIDWINADH				);//28
READ_REG_OFFSET(OSD_VIDWIN0ADL				);//2C
READ_REG_OFFSET(OSD_VIDWIN0ADR				);//2C
READ_REG_OFFSET(OSD_VIDWIN1ADL				);//30
READ_REG_OFFSET(OSD_VIDWIN1ADR				);//30
READ_REG_OFFSET(OSD_OSDWINADH				);//34
READ_REG_OFFSET(OSD_OSDWIN0ADL				);//38
READ_REG_OFFSET(OSD_OSDWIN0ADR				);//38
READ_REG_OFFSET(OSD_OSDWIN1ADL				);//3C
READ_REG_OFFSET(OSD_OSDWIN1ADR				);//3C
READ_REG_OFFSET(OSD_BASEPX				);//40
READ_REG_OFFSET(OSD_BASEPY				);//44
READ_REG_OFFSET(OSD_VIDWIN0XP				);//48
READ_REG_OFFSET(OSD_VIDWIN0YP				);//4C
READ_REG_OFFSET(OSD_VIDWIN0XL				);//50
READ_REG_OFFSET(OSD_VIDWIN0YL				);//54
READ_REG_OFFSET(OSD_VIDWIN1XP				);//58
READ_REG_OFFSET(OSD_VIDWIN1YP				);//5C
READ_REG_OFFSET(OSD_VIDWIN1XL				);//60
READ_REG_OFFSET(OSD_VIDWIN1YL				);//64
READ_REG_OFFSET(OSD_OSDWIN0XP				);//68
READ_REG_OFFSET(OSD_OSDWIN0YP				);//6C
READ_REG_OFFSET(OSD_OSDWIN0XL				);//70
READ_REG_OFFSET(OSD_OSDWIN0YL				);//74
READ_REG_OFFSET(OSD_OSDWIN1XP				);//78
READ_REG_OFFSET(OSD_OSDWIN1YP				);//7C
READ_REG_OFFSET(OSD_OSDWIN1XL				);//80
READ_REG_OFFSET(OSD_OSDWIN1YL				);//84
READ_REG_OFFSET(OSD_CURXP				);//88
READ_REG_OFFSET(OSD_CURYP				);//8C
READ_REG_OFFSET(OSD_CURXL				);//90
READ_REG_OFFSET(OSD_CURYL				);//94
READ_REG_OFFSET(OSD_W0BMP01				);//A0
READ_REG_OFFSET(OSD_W0BMP23				);//A4
READ_REG_OFFSET(OSD_W0BMP45				);//A8
READ_REG_OFFSET(OSD_W0BMP67				);//AC
READ_REG_OFFSET(OSD_W0BMP89				);//B0
READ_REG_OFFSET(OSD_W0BMPAB				);//B4
READ_REG_OFFSET(OSD_W0BMPCD				);//B8
READ_REG_OFFSET(OSD_W0BMPEF				);//BC
READ_REG_OFFSET(OSD_W1BMP01				);//C0
READ_REG_OFFSET(OSD_W1BMP23				);//C4
READ_REG_OFFSET(OSD_W1BMP45				);//C8
READ_REG_OFFSET(OSD_W1BMP67				);//CC
READ_REG_OFFSET(OSD_W1BMP89				);//D0
READ_REG_OFFSET(OSD_W1BMPAB				);//D4
READ_REG_OFFSET(OSD_W1BMPCD				);//D8
READ_REG_OFFSET(OSD_W1BMPEF				);//DC
READ_REG_OFFSET(OSD_VBNDRY				);//E0
READ_REG_OFFSET(OSD_EXTMODE				);//E4
READ_REG_OFFSET(OSD_MISCCTL				);//E8
READ_REG_OFFSET(OSD_CLUTRAMYCB				);//EC
READ_REG_OFFSET(OSD_CLUTRAMCR				);//F0
READ_REG_OFFSET(OSD_TRANSPVAL				);//F4
READ_REG_OFFSET(OSD_TRANSPVALL				);//F4
READ_REG_OFFSET(OSD_TRANSPVALU				);//F8
READ_REG_OFFSET(OSD_TRANSPBMPIDX			);//FC
READ_REG_OFFSET(OSD_PPVWIN0ADR				);//FC
}
#endif


#if defined(ARCH_DAVINCI_DM355)
static void print_regs_dm355(void) {

SET_BASE_OFFSET(OFFSET_BASE_REGISTER_DM355_VENC);

READ_REG_OFFSET(VENC_VMOD);
READ_REG_OFFSET(VENC_VIDCTL);
READ_REG_OFFSET(VENC_VDPRO);
READ_REG_OFFSET(VENC_SYNCCTL);
READ_REG_OFFSET(VENC_HSPLS);
READ_REG_OFFSET(VENC_VSPLS);
READ_REG_OFFSET(VENC_HINT);
READ_REG_OFFSET(VENC_HSTART);
READ_REG_OFFSET(VENC_HVALID);
READ_REG_OFFSET(VENC_VINT);
READ_REG_OFFSET(VENC_VSTART);
READ_REG_OFFSET(VENC_VVALID);
READ_REG_OFFSET(VENC_HSDLY);
READ_REG_OFFSET(VENC_VSDLY);
READ_REG_OFFSET(VENC_YCCCTL);
READ_REG_OFFSET(VENC_RGBCTL);
READ_REG_OFFSET(VENC_RGBCLP);
READ_REG_OFFSET(VENC_LINECTL);
READ_REG_OFFSET(VENC_CULLLINE);
READ_REG_OFFSET(VENC_LCDOUT);
READ_REG_OFFSET(VENC_BRTS);
READ_REG_OFFSET(VENC_BRTW);
READ_REG_OFFSET(VENC_ACCTL);
READ_REG_OFFSET(VENC_PWMP);
READ_REG_OFFSET(VENC_PWMW);
READ_REG_OFFSET(VENC_DCLKCTL);
READ_REG_OFFSET(VENC_DCLKPTN0);
READ_REG_OFFSET(VENC_DCLKPTN1);
READ_REG_OFFSET(VENC_DCLKPTN2);
READ_REG_OFFSET(VENC_DCLKPTN3);
READ_REG_OFFSET(VENC_DCLKPTN0A);
READ_REG_OFFSET(VENC_DCLKPTN1A);
READ_REG_OFFSET(VENC_DCLKPTN2A);
READ_REG_OFFSET(VENC_DCLKPTN3A);
READ_REG_OFFSET(VENC_DCLKHS);
READ_REG_OFFSET(VENC_DCLKHSA);
READ_REG_OFFSET(VENC_DCLKHR);
READ_REG_OFFSET(VENC_DCLKVS);
READ_REG_OFFSET(VENC_DCLKVR);
READ_REG_OFFSET(VENC_CAPCTL);
READ_REG_OFFSET(VENC_CAPDO);
READ_REG_OFFSET(VENC_CAPDE);
READ_REG_OFFSET(VENC_ATR0);
READ_REG_OFFSET(VENC_ATR1);
READ_REG_OFFSET(VENC_ATR2);
READ_REG_OFFSET(VENC_VSTAT);
READ_REG_OFFSET(VENC_RAMADR);
READ_REG_OFFSET(VENC_RAMPORT);
READ_REG_OFFSET(VENC_DACTST);
READ_REG_OFFSET(VENC_YCOLVL);
READ_REG_OFFSET(VENC_SCPROG);
READ_REG_OFFSET(VENC_CVBS);
READ_REG_OFFSET(VENC_CMPNT);
READ_REG_OFFSET(VENC_ETMG0);
READ_REG_OFFSET(VENC_ETMG1);
READ_REG_OFFSET(VENC_ETMG2);
READ_REG_OFFSET(VENC_ETMG3);
READ_REG_OFFSET(VENC_DACSEL);
READ_REG_OFFSET(VENC_ARGBX0);
READ_REG_OFFSET(VENC_ARGBX1);
READ_REG_OFFSET(VENC_ARGBX2);
READ_REG_OFFSET(VENC_ARGBX3);
READ_REG_OFFSET(VENC_ARGBX4);
READ_REG_OFFSET(VENC_DRGBX0);
READ_REG_OFFSET(VENC_DRGBX1);
READ_REG_OFFSET(VENC_DRGBX2);
READ_REG_OFFSET(VENC_DRGBX3);
READ_REG_OFFSET(VENC_DRGBX4);
READ_REG_OFFSET(VENC_VSTARTA);
READ_REG_OFFSET(VENC_OSDCLK0);
READ_REG_OFFSET(VENC_OSDCLK1);
READ_REG_OFFSET(VENC_HVLDCL0);
READ_REG_OFFSET(VENC_HVLDCL1);
READ_REG_OFFSET(VENC_OSDHADV);
READ_REG_OFFSET(VENC_CLKCTL);
READ_REG_OFFSET(VENC_GAMCTL);
READ_REG_OFFSET(VENC_XHINTVL);

SET_BASE_OFFSET(OFFSET_BASE_REGISTER_DM355_CCDC);

READ_REG_OFFSET(SYNCEN);
READ_REG_OFFSET(MODESET);
READ_REG_OFFSET(HDWIDTH);
READ_REG_OFFSET(VDWIDTH);
READ_REG_OFFSET(PPLN);
READ_REG_OFFSET(LPFR);
READ_REG_OFFSET(SPH);
READ_REG_OFFSET(NPH);
READ_REG_OFFSET(SLV0 );
READ_REG_OFFSET(SLV1 );
READ_REG_OFFSET(NLV );
READ_REG_OFFSET(CULH );
READ_REG_OFFSET(CULV );
READ_REG_OFFSET(HSIZE );
READ_REG_OFFSET(SDOFST );
READ_REG_OFFSET(STADRH );
READ_REG_OFFSET(STADRL );
READ_REG_OFFSET(CLAMP );
READ_REG_OFFSET(DCSUB );
READ_REG_OFFSET(COLPTN );
READ_REG_OFFSET(BLKCMP0 );
READ_REG_OFFSET(BLKCMP1 );
READ_REG_OFFSET(MEDFILT );
READ_REG_OFFSET(RYEGAIN );
READ_REG_OFFSET(GRCYGAIN );
READ_REG_OFFSET(GBGGAIN );
READ_REG_OFFSET(BMGGAIN );
READ_REG_OFFSET(OFFSET );
READ_REG_OFFSET(OUTCLIP );
READ_REG_OFFSET(VDINT0 );
READ_REG_OFFSET(VDINT1 );
READ_REG_OFFSET(RSV0 );
READ_REG_OFFSET(GAMMAWD );
READ_REG_OFFSET(REC656IF );
READ_REG_OFFSET(CCDCFG );
READ_REG_OFFSET(FMTCFG );
READ_REG_OFFSET(FMTPLEN );
READ_REG_OFFSET(FMTSPH );
READ_REG_OFFSET(FMTLNH );
READ_REG_OFFSET(FMTSLV );
READ_REG_OFFSET(FMTLNV );
READ_REG_OFFSET(FMTRLEN );
READ_REG_OFFSET(FMTHCNT );
READ_REG_OFFSET(FMTPGM_VF0 );
READ_REG_OFFSET(FMTPGM_VF1 );
READ_REG_OFFSET(FMTPGM_AP0 );
READ_REG_OFFSET(FMTPGM_AP1 );
READ_REG_OFFSET(FMTPGM_AP2 );
READ_REG_OFFSET(FMTPGM_AP3 );
READ_REG_OFFSET(FMTPGM_AP4 );
READ_REG_OFFSET(FMTPGM_AP5 );
READ_REG_OFFSET(FMTPGM_AP6 );
READ_REG_OFFSET(FMTPGM_AP7 );
READ_REG_OFFSET(LSCCFG1 );
READ_REG_OFFSET(LSCCFG2 );
READ_REG_OFFSET(LSCH0 );
READ_REG_OFFSET(LSCV0 );
READ_REG_OFFSET(LSCKH );
READ_REG_OFFSET(LSCKV );
READ_REG_OFFSET(LSCMEMCTL );
READ_REG_OFFSET(LSCMEMD );
READ_REG_OFFSET(LSCMEMQ );
READ_REG_OFFSET(DFCCTL );
READ_REG_OFFSET(DFCVSAT );
READ_REG_OFFSET(DFCMEMCTL );
READ_REG_OFFSET(DFCMEM0 );
READ_REG_OFFSET(DFCMEM1 );
READ_REG_OFFSET(DFCMEM2 );
READ_REG_OFFSET(DFCMEM3 );
READ_REG_OFFSET(DFCMEM4 );
READ_REG_OFFSET(CSCCTL );
READ_REG_OFFSET(CSCM0 );
READ_REG_OFFSET(CSCM1 );
READ_REG_OFFSET(CSCM2 );
READ_REG_OFFSET(CSCM3 );
READ_REG_OFFSET(CSCM4 );
READ_REG_OFFSET(CSCM5 );
READ_REG_OFFSET(CSCM6 );
READ_REG_OFFSET(CSCM7 );
READ_REG_OFFSET(DATAOFST );

SET_BASE_OFFSET(OFFSET_BASE_REGISTER_DM355_OSD);

READ_REG_OFFSET(OSD_MODE ); //0x00
READ_REG_OFFSET(OSD_VIDWINMD ); //0x04
READ_REG_OFFSET(OSD_OSDWIN0MD ); //0x08
READ_REG_OFFSET(OSD_OSDWIN1MD ); //0x0C
READ_REG_OFFSET(OSD_OSDATRMD ); //0x0C
READ_REG_OFFSET(OSD_RECTCUR ); //0x10
READ_REG_OFFSET(OSD_VIDWIN0OFST ); //0x18
READ_REG_OFFSET(OSD_VIDWIN1OFST ); //0x1C
READ_REG_OFFSET(OSD_OSDWIN0OFST ); //0x20
READ_REG_OFFSET(OSD_OSDWIN1OFST ); //0x24
READ_REG_OFFSET(OSD_VIDWINADH ); //0x28
READ_REG_OFFSET(OSD_VIDWIN0ADL ); //0x2C
READ_REG_OFFSET(OSD_VIDWIN0ADR ); //0x2C
READ_REG_OFFSET(OSD_VIDWIN1ADL ); //0x30
READ_REG_OFFSET(OSD_VIDWIN1ADR ); //0x30
READ_REG_OFFSET(OSD_OSDWINADH ); //0x34
READ_REG_OFFSET(OSD_OSDWIN0ADL ); //0x38
READ_REG_OFFSET(OSD_OSDWIN0ADR ); //0x38
READ_REG_OFFSET(OSD_OSDWIN1ADL ); //0x3C
READ_REG_OFFSET(OSD_OSDWIN1ADR ); //0x3C
READ_REG_OFFSET(OSD_BASEPX ); //0x40
READ_REG_OFFSET(OSD_BASEPY ); //0x44
READ_REG_OFFSET(OSD_VIDWIN0XP ); //0x48
READ_REG_OFFSET(OSD_VIDWIN0YP ); //0x4C
READ_REG_OFFSET(OSD_VIDWIN0XL ); //0x50
READ_REG_OFFSET(OSD_VIDWIN0YL ); //0x54
READ_REG_OFFSET(OSD_VIDWIN1XP ); //0x58
READ_REG_OFFSET(OSD_VIDWIN1YP ); //0x5C
READ_REG_OFFSET(OSD_VIDWIN1XL ); //0x60
READ_REG_OFFSET(OSD_VIDWIN1YL ); //0x64
READ_REG_OFFSET(OSD_OSDWIN0XP ); //0x68
READ_REG_OFFSET(OSD_OSDWIN0YP ); //0x6C
READ_REG_OFFSET(OSD_OSDWIN0XL ); //0x70
READ_REG_OFFSET(OSD_OSDWIN0YL ); //0x74
READ_REG_OFFSET(OSD_OSDWIN1XP ); //0x78
READ_REG_OFFSET(OSD_OSDWIN1YP ); //0x7C
READ_REG_OFFSET(OSD_OSDWIN1XL ); //0x80
READ_REG_OFFSET(OSD_OSDWIN1YL ); //0x84
READ_REG_OFFSET(OSD_CURXP ); //0x88
READ_REG_OFFSET(OSD_CURYP ); //0x8C
READ_REG_OFFSET(OSD_CURXL ); //0x90
READ_REG_OFFSET(OSD_CURYL ); //0x94
READ_REG_OFFSET(OSD_W0BMP01 ); //0xA0
READ_REG_OFFSET(OSD_W0BMP23 ); //0xA4
READ_REG_OFFSET(OSD_W0BMP45 ); //0xA8
READ_REG_OFFSET(OSD_W0BMP67 ); //0xAC
READ_REG_OFFSET(OSD_W0BMP89 ); //0xB0
READ_REG_OFFSET(OSD_W0BMPAB ); //0xB4
READ_REG_OFFSET(OSD_W0BMPCD ); //0xB8
READ_REG_OFFSET(OSD_W0BMPEF ); //0xBC
READ_REG_OFFSET(OSD_W1BMP01 ); //0xC0
READ_REG_OFFSET(OSD_W1BMP23 ); //0xC4
READ_REG_OFFSET(OSD_W1BMP45 ); //0xC8
READ_REG_OFFSET(OSD_W1BMP67 ); //0xCC
READ_REG_OFFSET(OSD_W1BMP89 ); //0xD0
READ_REG_OFFSET(OSD_W1BMPAB ); //0xD4
READ_REG_OFFSET(OSD_W1BMPCD ); //0xD8
READ_REG_OFFSET(OSD_W1BMPEF ); //0xDC
READ_REG_OFFSET(OSD_VBNDRY ); //0xE0
READ_REG_OFFSET(OSD_EXTMODE ); //0xE4
READ_REG_OFFSET(OSD_MISCCTL ); //0xE8
READ_REG_OFFSET(OSD_CLUTRAMYCB ); //0xEC
READ_REG_OFFSET(OSD_CLUTRAMCR ); //0xF0
READ_REG_OFFSET(OSD_TRANSPVAL ); //0xF4
READ_REG_OFFSET(OSD_TRANSPVALL ); //0xF4
READ_REG_OFFSET(OSD_TRANSPVALU ); //0xF8
READ_REG_OFFSET(OSD_TRANSPBMPIDX ); //0xFC
READ_REG_OFFSET(OSD_PPVWIN0ADR ); //0xFC


SET_BASE_OFFSET(OFFSET_BASE_REGISTER_DM355_IPIPE);

/* IPIPE Register Offsets from the base address */

READ_REG_OFFSET(IPIPE_EN ); //0x0000
READ_REG_OFFSET(IPIPE_MODE ); //0x0004
READ_REG_OFFSET(IPIPE_DPATHS ); //0x0008
READ_REG_OFFSET(IPIPE_COLPAT ); //0x000C
READ_REG_OFFSET(IPIPE_VST ); //0x0010
READ_REG_OFFSET(IPIPE_VSZ ); //0x0014
READ_REG_OFFSET(IPIPE_HST ); //0x0018
READ_REG_OFFSET(IPIPE_HSZ ); //0x001C
/*gated clock enable*/
READ_REG_OFFSET(GCL_ARM ); //0x0024
READ_REG_OFFSET(GCL_CCD ); //0x0028
READ_REG_OFFSET(GCL_SDR ); //0x002C
/* Internal Memory Access */
READ_REG_OFFSET(RAM_MODE ); //0x0030
READ_REG_OFFSET(RAM_ADR ); //0x0034
READ_REG_OFFSET(RAM_WDT ); //0x0038
READ_REG_OFFSET(RAM_RDT ); //0x003C
/* Interrupts */
READ_REG_OFFSET(IRQ_EN ); //0x0040
READ_REG_OFFSET(IRQ_RZA ); //0x0044
READ_REG_OFFSET(IRQ_RZB ); //0x0048
/* Defect Correction */
READ_REG_OFFSET(DFC_EN ); //0x004C
READ_REG_OFFSET(DFC_SEL ); //0x0050
READ_REG_OFFSET(DFC_ADR ); //0x0054
READ_REG_OFFSET(DFC_SIZE ); //0x0058
/* Programmable Noise Filter */
READ_REG_OFFSET(D2F_EN ); //0x005C
READ_REG_OFFSET(D2F_CFG ); //0x0060
READ_REG_OFFSET(D2F_THR ); //0x0064
READ_REG_OFFSET(D2F_STR ); //0x00E4
/* PreFilter */
READ_REG_OFFSET(PRE_EN ); //0x0164
READ_REG_OFFSET(PRE_TYP ); //0x0168
READ_REG_OFFSET(PRE_SHF ); //0x016C
READ_REG_OFFSET(PRE_GAIN ); //0x0170
READ_REG_OFFSET(PRE_THR_G ); //0x0174
READ_REG_OFFSET(PRE_THR_B ); //0x0178
READ_REG_OFFSET(PRE_THR_1 ); //0x017C
/* White Balance */
READ_REG_OFFSET(WB2_DGN ); //0x0180
READ_REG_OFFSET(WB2_WG_R ); //0x0184
READ_REG_OFFSET(WB2_WG_GR ); //0x0188
READ_REG_OFFSET(WB2_WG_GB ); //0x018C
READ_REG_OFFSET(WB2_WG_B ); //0x0190

/* RGB to RGB conversion (include GAMMA correction) */
READ_REG_OFFSET(RGB_MUL_RR ); //0x01F4

/* Defect Correction */
READ_REG_OFFSET(DFC_EN ); //0x004C
READ_REG_OFFSET(DFC_SEL ); //0x0050
READ_REG_OFFSET(DFC_ADR ); //0x0054
READ_REG_OFFSET(DFC_SIZ ); //0x0058
/* Programmable Noise Filter */
READ_REG_OFFSET(D2F_EN ); //0x005C
READ_REG_OFFSET(D2F_CFG ); //0x0060
READ_REG_OFFSET(DFC_THR ); //0x0064
READ_REG_OFFSET(D2F_STR ); //0x00E4
/* PreFilter */
READ_REG_OFFSET(PRE_EN ); //0x0164
READ_REG_OFFSET(PRE_TYP ); //0x0168
READ_REG_OFFSET(PRE_SHF ); //0x016C
READ_REG_OFFSET(PRE_GAIN ); //0x0170
READ_REG_OFFSET(PRE_THR_G ); //0x0174
READ_REG_OFFSET(PRE_THR_B ); //0x0178
READ_REG_OFFSET(PRE_THR_1 ); //0x017C
/* White Balance */
READ_REG_OFFSET(WB2_DGN ); //0x0180
READ_REG_OFFSET(WB2_WG_R ); //0x0184
READ_REG_OFFSET(WB2_WG_GR ); //0x0188
READ_REG_OFFSET(WB2_WG_GB ); //0x018C
READ_REG_OFFSET(WB2_WG_B ); //0x0190

/* RGB to RGB conversion (include GAMMA correction) */
READ_REG_OFFSET(RGB_MUL_RR ); //0x01F4
READ_REG_OFFSET(RGB_MUL_GR ); //0x01F8
READ_REG_OFFSET(RGB_MUL_BR ); //0x01FC
READ_REG_OFFSET(RGB_MUL_RG ); //0x0200
READ_REG_OFFSET(RGB_MUL_GG ); //0x0204
READ_REG_OFFSET(RGB_MUL_BG ); //0x0208
READ_REG_OFFSET(RGB_MUL_RB ); //0x020C

READ_REG_OFFSET(RGB_MUL_GB ); //0x0210
READ_REG_OFFSET(RGB_MUL_BB ); //0x0214
READ_REG_OFFSET(RGB_MUL_OR ); //0x0218
READ_REG_OFFSET(RGB_MUL_OG ); //0x021C
READ_REG_OFFSET(RGB_MUL_OB ); //0x0220
READ_REG_OFFSET(GMM_CFG ); //0x0224

/* RGB to YUV(YCbCr) conversion */
READ_REG_OFFSET(YUV_ADJ ); //0x0228
READ_REG_OFFSET(YUV_MUL_RY ); //0x022C
READ_REG_OFFSET(YUV_MUL_GY ); //0x0230
READ_REG_OFFSET(YUV_MUL_BY ); //0x0234
READ_REG_OFFSET(YUV_MUL_RCB ); //0x0238
READ_REG_OFFSET(YUV_MUL_GCB ); //0x023C
READ_REG_OFFSET(YUV_MUL_BCB ); //0x0240
READ_REG_OFFSET(YUV_MUL_RCR ); //0x0244
READ_REG_OFFSET(YUV_MUL_GCR ); //0x0248
READ_REG_OFFSET(YUV_MUL_BCR ); //0x024C
READ_REG_OFFSET(YUV_OFT_Y ); //0x0250
READ_REG_OFFSET(YUV_OFT_CB ); //0x0254
READ_REG_OFFSET(YUV_OFT_CR ); //0x0258
READ_REG_OFFSET(YUV_Y_MIN ); //0x025C
READ_REG_OFFSET(YUV_Y_MAX ); //0x0260
READ_REG_OFFSET(YUV_C_MIN ); //0x0264
READ_REG_OFFSET(YUV_C_MAX ); //0x0268
READ_REG_OFFSET(YUV_PHS ); //0x026C

/* Edge Enhancer */
READ_REG_OFFSET(YEE_EN ); //0x0270
READ_REG_OFFSET(YEE_EMF ); //0x0274
READ_REG_OFFSET(YEE_SHF ); //0x0278
READ_REG_OFFSET(YEE_MUL_00 ); //0x027C
READ_REG_OFFSET(YEE_MUL_01 ); //0x0280
READ_REG_OFFSET(YEE_MUL_02 ); //0x0284
READ_REG_OFFSET(YEE_MUL_10 ); //0x0288
READ_REG_OFFSET(YEE_MUL_11 ); //0x028C
READ_REG_OFFSET(YEE_MUL_12 ); //0x0290
READ_REG_OFFSET(YEE_MUL_20 ); //0x0294
READ_REG_OFFSET(YEE_MUL_21 ); //0x0298
READ_REG_OFFSET(YEE_MUL_22 ); //0x029C

/* False Color Suppression */
READ_REG_OFFSET(FCS_EN ); //0x02A0
READ_REG_OFFSET(FCS_TYP ); //0x02A4
READ_REG_OFFSET(FCS_SHF_Y ); //0x02A8
READ_REG_OFFSET(FCS_SHF_C ); //0x02AC
READ_REG_OFFSET(FCS_THR ); //0x02B0
READ_REG_OFFSET(FCS_SGN ); //0x02B4
READ_REG_OFFSET(FCS_LTH ); //0x02B8

/* Resizer */
READ_REG_OFFSET(RSZ_SEQ ); //0x02BC
READ_REG_OFFSET(RSZ_AAL ); //0x02C0

/* Resizer Rescale Parameters */
READ_REG_OFFSET(RSZ_EN_0 ); //0x02C4
READ_REG_OFFSET(RSZ_EN_1 ); //0x0334

}
#endif

static int __init mod_init(void) {
	printk(KERN_DEBUG "mod_init\n");
	/*
	 ret = set_base_addr();
	 if(ret != 0)
	 return ret;
	 */
#if defined(ARCH_DAVINCI_DM355)
	print_regs_dm355();
#endif

#if defined(CONFIG_MACH_DM365_LEOPARD)
	print_regs_dm365();
#endif

	//return 0;
	printk( KERN_INFO "\nIgnore the following error, because module unload automatic!\n\n");
	return -EIO;
}

static void __exit mod_exit(void) {
	printk(KERN_DEBUG "mod_exit\n");
	//release_mem_region(BASE_REGISTER_START_ADDR, BASE_REGISTER_DM355_SIZE);
}

module_init(mod_init);
module_exit(mod_exit);

MODULE_DESCRIPTION("Read davinci register");
MODULE_AUTHOR("Klaus Schwarzkopf <schwarzkopf@sensortherm.de>");
MODULE_LICENSE("GPL v2");
