/*
 * davinci_read_regs.c
 *
 *
 *  Created on: 20.01.2011
 *      Author: Klaus Schwarzkopf <schwarzkopf@sensortherm.de>
 *
 * This package is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#include <linux/log2.h>
#include <linux/slab.h>
#include <linux/kernel.h>
#include <linux/module.h>
#include <video/davinci_vpbe.h>
#include <linux/platform_device.h>

#include "../davinci/dm355_ccdc_regs.h"
#include "../../../char/dm355_ipipe_hw.h"

#include <mach/hardware.h>
#include <mach/io.h>

#include <asm/io.h>

extern u32 venc_reg_in(u32 offset);

//#define READ_REG(x) (printk( KERN_INFO "%s\t 0x%08x 0x%08x\n", #x, x, venc_reg_in(x)))
#define BASE_REGISTER_START_ADDR		0x01c70000
#define BASE_REGISTER_END_ADDR			0x01c71404
#define BASE_REGISTER_SIZE				(BASE_REGISTER_END_ADDR-BASE_REGISTER_START_ADDR)

#define OFFSET_BASE_REGISTER_VPSSCLK	0x0000
#define OFFSET_BASE_REGISTER_H3A		0x0080
#define OFFSET_BASE_REGISTER_IPIPEIF	0x0100
#define OFFSET_BASE_REGISTER_OSD		0x0200
#define OFFSET_BASE_REGISTER_VENC		0x0400
#define OFFSET_BASE_REGISTER_CCDC		0x0600
#define OFFSET_BASE_REGISTER_VPSSBL		0x0800
#define OFFSET_BASE_REGISTER_IPIPE		0x1000

#define base_addr  IO_ADDRESS(BASE_REGISTER_START_ADDR)
u32 base_offset = 0;

static inline u32 regr(u32 offset) {
	return __raw_readl(base_addr + base_offset + offset);
}

static inline void regw(u32 val, u32 offset) {
	__raw_writel(val, base_addr + base_offset + offset);
}

#define READ_REG(x) (printk( KERN_INFO "%20s\t 0x%08x 0x%08x\n", #x, x, regr(x)))

#define SET_BASE_OFFSET(x) (printk( KERN_INFO "\n%s\t 0x%08x\n\n", #x, base_offset=x))

static void print_regs(void) {

SET_BASE_OFFSET(OFFSET_BASE_REGISTER_VENC);

READ_REG(VENC_VMOD);
READ_REG(VENC_VIDCTL);
READ_REG(VENC_VDPRO);
READ_REG(VENC_SYNCCTL);
READ_REG(VENC_HSPLS);
READ_REG(VENC_VSPLS);
READ_REG(VENC_HINT);
READ_REG(VENC_HSTART);
READ_REG(VENC_HVALID);
READ_REG(VENC_VINT);
READ_REG(VENC_VSTART);
READ_REG(VENC_VVALID);
READ_REG(VENC_HSDLY);
READ_REG(VENC_VSDLY);
READ_REG(VENC_YCCCTL);
READ_REG(VENC_RGBCTL);
READ_REG(VENC_RGBCLP);
READ_REG(VENC_LINECTL);
READ_REG(VENC_CULLLINE);
READ_REG(VENC_LCDOUT);
READ_REG(VENC_BRTS);
READ_REG(VENC_BRTW);
READ_REG(VENC_ACCTL);
READ_REG(VENC_PWMP);
READ_REG(VENC_PWMW);
READ_REG(VENC_DCLKCTL);
READ_REG(VENC_DCLKPTN0);
READ_REG(VENC_DCLKPTN1);
READ_REG(VENC_DCLKPTN2);
READ_REG(VENC_DCLKPTN3);
READ_REG(VENC_DCLKPTN0A);
READ_REG(VENC_DCLKPTN1A);
READ_REG(VENC_DCLKPTN2A);
READ_REG(VENC_DCLKPTN3A);
READ_REG(VENC_DCLKHS);
READ_REG(VENC_DCLKHSA);
READ_REG(VENC_DCLKHR);
READ_REG(VENC_DCLKVS);
READ_REG(VENC_DCLKVR);
READ_REG(VENC_CAPCTL);
READ_REG(VENC_CAPDO);
READ_REG(VENC_CAPDE);
READ_REG(VENC_ATR0);
READ_REG(VENC_ATR1);
READ_REG(VENC_ATR2);
READ_REG(VENC_VSTAT);
READ_REG(VENC_RAMADR);
READ_REG(VENC_RAMPORT);
READ_REG(VENC_DACTST);
READ_REG(VENC_YCOLVL);
READ_REG(VENC_SCPROG);
READ_REG(VENC_CVBS);
READ_REG(VENC_CMPNT);
READ_REG(VENC_ETMG0);
READ_REG(VENC_ETMG1);
READ_REG(VENC_ETMG2);
READ_REG(VENC_ETMG3);
READ_REG(VENC_DACSEL);
READ_REG(VENC_ARGBX0);
READ_REG(VENC_ARGBX1);
READ_REG(VENC_ARGBX2);
READ_REG(VENC_ARGBX3);
READ_REG(VENC_ARGBX4);
READ_REG(VENC_DRGBX0);
READ_REG(VENC_DRGBX1);
READ_REG(VENC_DRGBX2);
READ_REG(VENC_DRGBX3);
READ_REG(VENC_DRGBX4);
READ_REG(VENC_VSTARTA);
READ_REG(VENC_OSDCLK0);
READ_REG(VENC_OSDCLK1);
READ_REG(VENC_HVLDCL0);
READ_REG(VENC_HVLDCL1);
READ_REG(VENC_OSDHADV);
READ_REG(VENC_CLKCTL);
READ_REG(VENC_GAMCTL);
READ_REG(VENC_XHINTVL);

SET_BASE_OFFSET(OFFSET_BASE_REGISTER_CCDC);

READ_REG(SYNCEN);
READ_REG(MODESET);
READ_REG(HDWIDTH);
READ_REG(VDWIDTH);
READ_REG(PPLN);
READ_REG(LPFR);
READ_REG(SPH);
READ_REG(NPH);
READ_REG(SLV0 );
READ_REG(SLV1 );
READ_REG(NLV );
READ_REG(CULH );
READ_REG(CULV );
READ_REG(HSIZE );
READ_REG(SDOFST );
READ_REG(STADRH );
READ_REG(STADRL );
READ_REG(CLAMP );
READ_REG(DCSUB );
READ_REG(COLPTN );
READ_REG(BLKCMP0 );
READ_REG(BLKCMP1 );
READ_REG(MEDFILT );
READ_REG(RYEGAIN );
READ_REG(GRCYGAIN );
READ_REG(GBGGAIN );
READ_REG(BMGGAIN );
READ_REG(OFFSET );
READ_REG(OUTCLIP );
READ_REG(VDINT0 );
READ_REG(VDINT1 );
READ_REG(RSV0 );
READ_REG(GAMMAWD );
READ_REG(REC656IF );
READ_REG(CCDCFG );
READ_REG(FMTCFG );
READ_REG(FMTPLEN );
READ_REG(FMTSPH );
READ_REG(FMTLNH );
READ_REG(FMTSLV );
READ_REG(FMTLNV );
READ_REG(FMTRLEN );
READ_REG(FMTHCNT );
READ_REG(FMTPGM_VF0 );
READ_REG(FMTPGM_VF1 );
READ_REG(FMTPGM_AP0 );
READ_REG(FMTPGM_AP1 );
READ_REG(FMTPGM_AP2 );
READ_REG(FMTPGM_AP3 );
READ_REG(FMTPGM_AP4 );
READ_REG(FMTPGM_AP5 );
READ_REG(FMTPGM_AP6 );
READ_REG(FMTPGM_AP7 );
READ_REG(LSCCFG1 );
READ_REG(LSCCFG2 );
READ_REG(LSCH0 );
READ_REG(LSCV0 );
READ_REG(LSCKH );
READ_REG(LSCKV );
READ_REG(LSCMEMCTL );
READ_REG(LSCMEMD );
READ_REG(LSCMEMQ );
READ_REG(DFCCTL );
READ_REG(DFCVSAT );
READ_REG(DFCMEMCTL );
READ_REG(DFCMEM0 );
READ_REG(DFCMEM1 );
READ_REG(DFCMEM2 );
READ_REG(DFCMEM3 );
READ_REG(DFCMEM4 );
READ_REG(CSCCTL );
READ_REG(CSCM0 );
READ_REG(CSCM1 );
READ_REG(CSCM2 );
READ_REG(CSCM3 );
READ_REG(CSCM4 );
READ_REG(CSCM5 );
READ_REG(CSCM6 );
READ_REG(CSCM7 );
READ_REG(DATAOFST );

SET_BASE_OFFSET(OFFSET_BASE_REGISTER_OSD);

READ_REG(OSD_MODE ); //0x00
READ_REG(OSD_VIDWINMD ); //0x04
READ_REG(OSD_OSDWIN0MD ); //0x08
READ_REG(OSD_OSDWIN1MD ); //0x0C
READ_REG(OSD_OSDATRMD ); //0x0C
READ_REG(OSD_RECTCUR ); //0x10
READ_REG(OSD_VIDWIN0OFST ); //0x18
READ_REG(OSD_VIDWIN1OFST ); //0x1C
READ_REG(OSD_OSDWIN0OFST ); //0x20
READ_REG(OSD_OSDWIN1OFST ); //0x24
READ_REG(OSD_VIDWINADH ); //0x28
READ_REG(OSD_VIDWIN0ADL ); //0x2C
READ_REG(OSD_VIDWIN0ADR ); //0x2C
READ_REG(OSD_VIDWIN1ADL ); //0x30
READ_REG(OSD_VIDWIN1ADR ); //0x30
READ_REG(OSD_OSDWINADH ); //0x34
READ_REG(OSD_OSDWIN0ADL ); //0x38
READ_REG(OSD_OSDWIN0ADR ); //0x38
READ_REG(OSD_OSDWIN1ADL ); //0x3C
READ_REG(OSD_OSDWIN1ADR ); //0x3C
READ_REG(OSD_BASEPX ); //0x40
READ_REG(OSD_BASEPY ); //0x44
READ_REG(OSD_VIDWIN0XP ); //0x48
READ_REG(OSD_VIDWIN0YP ); //0x4C
READ_REG(OSD_VIDWIN0XL ); //0x50
READ_REG(OSD_VIDWIN0YL ); //0x54
READ_REG(OSD_VIDWIN1XP ); //0x58
READ_REG(OSD_VIDWIN1YP ); //0x5C
READ_REG(OSD_VIDWIN1XL ); //0x60
READ_REG(OSD_VIDWIN1YL ); //0x64
READ_REG(OSD_OSDWIN0XP ); //0x68
READ_REG(OSD_OSDWIN0YP ); //0x6C
READ_REG(OSD_OSDWIN0XL ); //0x70
READ_REG(OSD_OSDWIN0YL ); //0x74
READ_REG(OSD_OSDWIN1XP ); //0x78
READ_REG(OSD_OSDWIN1YP ); //0x7C
READ_REG(OSD_OSDWIN1XL ); //0x80
READ_REG(OSD_OSDWIN1YL ); //0x84
READ_REG(OSD_CURXP ); //0x88
READ_REG(OSD_CURYP ); //0x8C
READ_REG(OSD_CURXL ); //0x90
READ_REG(OSD_CURYL ); //0x94
READ_REG(OSD_W0BMP01 ); //0xA0
READ_REG(OSD_W0BMP23 ); //0xA4
READ_REG(OSD_W0BMP45 ); //0xA8
READ_REG(OSD_W0BMP67 ); //0xAC
READ_REG(OSD_W0BMP89 ); //0xB0
READ_REG(OSD_W0BMPAB ); //0xB4
READ_REG(OSD_W0BMPCD ); //0xB8
READ_REG(OSD_W0BMPEF ); //0xBC
READ_REG(OSD_W1BMP01 ); //0xC0
READ_REG(OSD_W1BMP23 ); //0xC4
READ_REG(OSD_W1BMP45 ); //0xC8
READ_REG(OSD_W1BMP67 ); //0xCC
READ_REG(OSD_W1BMP89 ); //0xD0
READ_REG(OSD_W1BMPAB ); //0xD4
READ_REG(OSD_W1BMPCD ); //0xD8
READ_REG(OSD_W1BMPEF ); //0xDC
READ_REG(OSD_VBNDRY ); //0xE0
READ_REG(OSD_EXTMODE ); //0xE4
READ_REG(OSD_MISCCTL ); //0xE8
READ_REG(OSD_CLUTRAMYCB ); //0xEC
READ_REG(OSD_CLUTRAMCR ); //0xF0
READ_REG(OSD_TRANSPVAL ); //0xF4
READ_REG(OSD_TRANSPVALL ); //0xF4
READ_REG(OSD_TRANSPVALU ); //0xF8
READ_REG(OSD_TRANSPBMPIDX ); //0xFC
READ_REG(OSD_PPVWIN0ADR ); //0xFC


SET_BASE_OFFSET(OFFSET_BASE_REGISTER_IPIPE);

/* IPIPE Register Offsets from the base address */

READ_REG(IPIPE_EN ); //0x0000
READ_REG(IPIPE_MODE ); //0x0004
READ_REG(IPIPE_DPATHS ); //0x0008
READ_REG(IPIPE_COLPAT ); //0x000C
READ_REG(IPIPE_VST ); //0x0010
READ_REG(IPIPE_VSZ ); //0x0014
READ_REG(IPIPE_HST ); //0x0018
READ_REG(IPIPE_HSZ ); //0x001C
/*gated clock enable*/
READ_REG(GCL_ARM ); //0x0024
READ_REG(GCL_CCD ); //0x0028
READ_REG(GCL_SDR ); //0x002C
/* Internal Memory Access */
READ_REG(RAM_MODE ); //0x0030
READ_REG(RAM_ADR ); //0x0034
READ_REG(RAM_WDT ); //0x0038
READ_REG(RAM_RDT ); //0x003C
/* Interrupts */
READ_REG(IRQ_EN ); //0x0040
READ_REG(IRQ_RZA ); //0x0044
READ_REG(IRQ_RZB ); //0x0048
/* Defect Correction */
READ_REG(DFC_EN ); //0x004C
READ_REG(DFC_SEL ); //0x0050
READ_REG(DFC_ADR ); //0x0054
READ_REG(DFC_SIZE ); //0x0058
/* Programmable Noise Filter */
READ_REG(D2F_EN ); //0x005C
READ_REG(D2F_CFG ); //0x0060
READ_REG(D2F_THR ); //0x0064
READ_REG(D2F_STR ); //0x00E4
/* PreFilter */
READ_REG(PRE_EN ); //0x0164
READ_REG(PRE_TYP ); //0x0168
READ_REG(PRE_SHF ); //0x016C
READ_REG(PRE_GAIN ); //0x0170
READ_REG(PRE_THR_G ); //0x0174
READ_REG(PRE_THR_B ); //0x0178
READ_REG(PRE_THR_1 ); //0x017C
/* White Balance */
READ_REG(WB2_DGN ); //0x0180
READ_REG(WB2_WG_R ); //0x0184
READ_REG(WB2_WG_GR ); //0x0188
READ_REG(WB2_WG_GB ); //0x018C
READ_REG(WB2_WG_B ); //0x0190

/* RGB to RGB conversion (include GAMMA correction) */
READ_REG(RGB_MUL_RR ); //0x01F4

/* Defect Correction */
READ_REG(DFC_EN ); //0x004C
READ_REG(DFC_SEL ); //0x0050
READ_REG(DFC_ADR ); //0x0054
READ_REG(DFC_SIZ ); //0x0058
/* Programmable Noise Filter */
READ_REG(D2F_EN ); //0x005C
READ_REG(D2F_CFG ); //0x0060
READ_REG(DFC_THR ); //0x0064
READ_REG(D2F_STR ); //0x00E4
/* PreFilter */
READ_REG(PRE_EN ); //0x0164
READ_REG(PRE_TYP ); //0x0168
READ_REG(PRE_SHF ); //0x016C
READ_REG(PRE_GAIN ); //0x0170
READ_REG(PRE_THR_G ); //0x0174
READ_REG(PRE_THR_B ); //0x0178
READ_REG(PRE_THR_1 ); //0x017C
/* White Balance */
READ_REG(WB2_DGN ); //0x0180
READ_REG(WB2_WG_R ); //0x0184
READ_REG(WB2_WG_GR ); //0x0188
READ_REG(WB2_WG_GB ); //0x018C
READ_REG(WB2_WG_B ); //0x0190

/* RGB to RGB conversion (include GAMMA correction) */
READ_REG(RGB_MUL_RR ); //0x01F4
READ_REG(RGB_MUL_GR ); //0x01F8
READ_REG(RGB_MUL_BR ); //0x01FC
READ_REG(RGB_MUL_RG ); //0x0200
READ_REG(RGB_MUL_GG ); //0x0204
READ_REG(RGB_MUL_BG ); //0x0208
READ_REG(RGB_MUL_RB ); //0x020C

READ_REG(RGB_MUL_GB ); //0x0210
READ_REG(RGB_MUL_BB ); //0x0214
READ_REG(RGB_MUL_OR ); //0x0218
READ_REG(RGB_MUL_OG ); //0x021C
READ_REG(RGB_MUL_OB ); //0x0220
READ_REG(GMM_CFG ); //0x0224

/* RGB to YUV(YCbCr) conversion */
READ_REG(YUV_ADJ ); //0x0228
READ_REG(YUV_MUL_RY ); //0x022C
READ_REG(YUV_MUL_GY ); //0x0230
READ_REG(YUV_MUL_BY ); //0x0234
READ_REG(YUV_MUL_RCB ); //0x0238
READ_REG(YUV_MUL_GCB ); //0x023C
READ_REG(YUV_MUL_BCB ); //0x0240
READ_REG(YUV_MUL_RCR ); //0x0244
READ_REG(YUV_MUL_GCR ); //0x0248
READ_REG(YUV_MUL_BCR ); //0x024C
READ_REG(YUV_OFT_Y ); //0x0250
READ_REG(YUV_OFT_CB ); //0x0254
READ_REG(YUV_OFT_CR ); //0x0258
READ_REG(YUV_Y_MIN ); //0x025C
READ_REG(YUV_Y_MAX ); //0x0260
READ_REG(YUV_C_MIN ); //0x0264
READ_REG(YUV_C_MAX ); //0x0268
READ_REG(YUV_PHS ); //0x026C

/* Edge Enhancer */
READ_REG(YEE_EN ); //0x0270
READ_REG(YEE_EMF ); //0x0274
READ_REG(YEE_SHF ); //0x0278
READ_REG(YEE_MUL_00 ); //0x027C
READ_REG(YEE_MUL_01 ); //0x0280
READ_REG(YEE_MUL_02 ); //0x0284
READ_REG(YEE_MUL_10 ); //0x0288
READ_REG(YEE_MUL_11 ); //0x028C
READ_REG(YEE_MUL_12 ); //0x0290
READ_REG(YEE_MUL_20 ); //0x0294
READ_REG(YEE_MUL_21 ); //0x0298
READ_REG(YEE_MUL_22 ); //0x029C

/* False Color Suppression */
READ_REG(FCS_EN ); //0x02A0
READ_REG(FCS_TYP ); //0x02A4
READ_REG(FCS_SHF_Y ); //0x02A8
READ_REG(FCS_SHF_C ); //0x02AC
READ_REG(FCS_THR ); //0x02B0
READ_REG(FCS_SGN ); //0x02B4
READ_REG(FCS_LTH ); //0x02B8

/* Resizer */
READ_REG(RSZ_SEQ ); //0x02BC
READ_REG(RSZ_AAL ); //0x02C0

/* Resizer Rescale Parameters */
READ_REG(RSZ_EN_0 ); //0x02C4
READ_REG(RSZ_EN_1 ); //0x0334

}

static int __init mod_init(void) {
	int ret = 0;

	printk(KERN_DEBUG "mod_init\n");
	/*
	 ret = set_base_addr();
	 if(ret != 0)
	 return ret;
	 */
	print_regs();
	return -EIO;
}

static void __exit mod_exit(void) {
	printk(KERN_DEBUG "mod_exit\n");
	//release_mem_region(BASE_REGISTER_START_ADDR, BASE_REGISTER_SIZE);
}

module_init(mod_init);
module_exit(mod_exit);

MODULE_DESCRIPTION("Read davinci register");
MODULE_AUTHOR("Klaus Schwarzkopf <schwarzkopf@sensortherm.de>");
MODULE_LICENSE("GPL v2");
