#
# Makefile for the video capture/playback device drivers.
#
mt9v126-objs := rw_i2c_reg.o mt9v126_core.o 

obj-$(CONFIG_SOC_CAMERA_MT9V126)	+= mt9v126.o

obj-$(CONFIG_DAVINCI_READ_REGS)		+= davinci_read_regs.o

